name: Spring-Boot-Idea-rush-Amazon EC2

on:
  push:
    branches:
      - main
env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.AWS_ECR_ADDRESS }}
  ECR_REPOSITORY: idea-rush
  IMAGE_TAG: latest
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $AWS_REGION

      - name: Build and Push Docker image
        env:
          ECR_REGISTRY: $ECR_REGISTRY
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/my-container-app:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/my-container-app:$IMAGE_TAG $ECR_REGISTRY/my-container-app:$IMAGE_TAG
          docker push $ECR_REGISTRY/my-container-app:$IMAGE_TAG
